package by.victor.jwd.controller.command;

public enum CommandName {
	AUTH, REGISTRATION, SAVENEWCUSTOMER, GOTOMAINPAGE,
	LOGOUT, GOTOCART, GOTOCATEGORY, GOTOCONTACT, GOTOPRODUCT, GOTOSIGNINPAGE,
	GOTOPROFILE, UPDATEPROFILE, ADDTOCART, DELETECARTITEM, GOTOADMINPAGE, BLOCKUSER,
	UNBLOCKUSER, MAKEADMIN, NEWORDER, SHOWORDERS, SHOWUSERS, CHANGESTATUS, USERDECLINE,
	ADDFOOTWEAR, NEWFOOTWEAR, CHANGEPASSWORD, GOTOCHANGEPASSWORD, GOTOADDFEATURES,
	GOTOITEMSPAGE, ADDCATEGORY, ADDCOLOR, ADDBRAND, ADDITEM, CHANGEITEMSTATUS,
	GOTOEDITFOOTWEAR, EDITFOOTWEAR, DELETEIMAGE, FASTORDER

}
