package by.victor.jwd.controller.command;

public enum CommandName {
	AUTH, REGISTRATION, SAVENEWCUSTOMER, GOTOMAINPAGE,
	LOGOUT, GOTOCART, GOTOCATEGORY, GOTOCONTACT, GOTOPRODUCT, GOTOSIGNINPAGE,
	GOTOPROFILE, UPDATEPROFILE, ADDTOCART, DELETECARTITEM, GOTOADMINPAGE, DELETECUSTOMER,
	NEWORDER, SHOWORDERS, SHOWUSERS

}
